# Install nginx and clone repository in /var/www/classicbox_site
# ln -s /var/www/classicbox_site/nginx/site.conf /etc/nginx/sites-enabled/site.conf
# rm /etc/nginx/sites-enabled/default
# sudo service nginx restart
# Follow guide: https://certbot.eff.org/instructions?ws=nginx&os=snap

server {
	listen 80;
	listen [::]:80;
	server_name classic-box.ru www.classic-box.ru;
	root /var/www/classicbox_site;

	location = /index {
		return 301 /;
	}

	location = /index.html {
		return 301 /;
	}

	location ~ \.html$ {
		rewrite ^(.*)\.html$ $1 permanent;
	}

	location / {
		try_files $uri $uri.html /index.html =404;
	}
}
