server {
	listen 80;
	listen [::]:80;
	server_name classic-box.ru www.classic-box.ru;
	root /var/www/classicbox_site;

	location = /index {
		return 301 /;
	}

	location = /index.html {
		return 301 /;
	}

	location ~ \.html$ {
		rewrite ^(.*)\.html$ $1 permanent;
	}

	location / {
		try_files $uri $uri.html /index.html =404;
	}
}
